import { ItemType, Rarity, BindType } from '@game/shared';

export function seedItemTemplates(): any[] {
  return [
    {
      id: 'item_gold_small',
      name: '小金币袋',
      type: ItemType.CONSUMABLE,
      rarity: Rarity.N,
      description: '打开后可获得1000金币。',
      icon: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=gold%20coin%20bag%20small%20game%20item%20icon&image_size=square',
      maxStack: 99,
      sellable: true,
      sellPrice: 50,
      bindType: BindType.UNBIND,
      usable: true,
      useEffect: { type: 'gain_currency', value: 1000, currencyType: 'gold' },
    },
    {
      id: 'item_gold_medium',
      name: '中金币袋',
      type: ItemType.CONSUMABLE,
      rarity: Rarity.R,
      description: '打开后可获得5000金币。',
      icon: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=gold%20coin%20bag%20medium%20game%20item%20icon&image_size=square',
      maxStack: 99,
      sellable: true,
      sellPrice: 200,
      bindType: BindType.UNBIND,
      usable: true,
      useEffect: { type: 'gain_currency', value: 5000, currencyType: 'gold' },
    },
    {
      id: 'item_gold_large',
      name: '大金币袋',
      type: ItemType.CONSUMABLE,
      rarity: Rarity.SR,
      description: '打开后可获得20000金币。',
      icon: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=gold%20coin%20bag%20large%20game%20item%20icon&image_size=square',
      maxStack: 99,
      sellable: true,
      sellPrice: 800,
      bindType: BindType.UNBIND,
      usable: true,
      useEffect: { type: 'gain_currency', value: 20000, currencyType: 'gold' },
    },
    {
      id: 'item_diamond_small',
      name: '小钻石箱',
      type: ItemType.CONSUMABLE,
      rarity: Rarity.SR,
      description: '打开后可获得100钻石。',
      icon: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=diamond%20chest%20small%20game%20item%20icon&image_size=square',
      maxStack: 99,
      sellable: false,
      sellPrice: 0,
      bindType: BindType.BIND,
      usable: true,
      useEffect: { type: 'gain_currency', value: 100, currencyType: 'diamond' },
    },
    {
      id: 'item_diamond_large',
      name: '大钻石箱',
      type: ItemType.CONSUMABLE,
      rarity: Rarity.SSR,
      description: '打开后可获得500钻石。',
      icon: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=diamond%20chest%20large%20game%20item%20icon&image_size=square',
      maxStack: 99,
      sellable: false,
      sellPrice: 0,
      bindType: BindType.BIND,
      usable: true,
      useEffect: { type: 'gain_currency', value: 500, currencyType: 'diamond' },
    },
    {
      id: 'item_exp_potion_n',
      name: '初级经验药水',
      type: ItemType.CONSUMABLE,
      rarity: Rarity.N,
      description: '使用后可为指定卡牌增加100经验值。',
      icon: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=exp%20potion%20green%20small%20game%20item%20icon&image_size=square',
      maxStack: 999,
      sellable: true,
      sellPrice: 20,
      bindType: BindType.UNBIND,
      usable: true,
      useEffect: { type: 'gain_exp', value: 100 },
    },
    {
      id: 'item_exp_potion_r',
      name: '中级经验药水',
      type: ItemType.CONSUMABLE,
      rarity: Rarity.R,
      description: '使用后可为指定卡牌增加500经验值。',
      icon: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=exp%20potion%20blue%20medium%20game%20item%20icon&image_size=square',
      maxStack: 999,
      sellable: true,
      sellPrice: 80,
      bindType: BindType.UNBIND,
      usable: true,
      useEffect: { type: 'gain_exp', value: 500 },
    },
    {
      id: 'item_exp_potion_sr',
      name: '高级经验药水',
      type: ItemType.CONSUMABLE,
      rarity: Rarity.SR,
      description: '使用后可为指定卡牌增加2000经验值。',
      icon: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=exp%20potion%20purple%20large%20game%20item%20icon&image_size=square',
      maxStack: 999,
      sellable: true,
      sellPrice: 300,
      bindType: BindType.UNBIND,
      usable: true,
      useEffect: { type: 'gain_exp', value: 2000 },
    },
    {
      id: 'item_exp_potion_ssr',
      name: '特级经验药水',
      type: ItemType.CONSUMABLE,
      rarity: Rarity.SSR,
      description: '使用后可为指定卡牌增加10000经验值。',
      icon: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=exp%20potion%20golden%20legendary%20game%20item%20icon&image_size=square',
      maxStack: 999,
      sellable: true,
      sellPrice: 1000,
      bindType: BindType.UNBIND,
      usable: true,
      useEffect: { type: 'gain_exp', value: 10000 },
    },
    {
      id: 'item_breakthrough_stone_r',
      name: '初级突破石',
      type: ItemType.MATERIAL,
      rarity: Rarity.R,
      description: '用于R及以下稀有度卡牌突破的材料。',
      icon: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=breakthrough%20stone%20blue%20common%20game%20item%20icon&image_size=square',
      maxStack: 999,
      sellable: true,
      sellPrice: 50,
      bindType: BindType.UNBIND,
      usable: false,
    },
    {
      id: 'item_breakthrough_stone_sr',
      name: '中级突破石',
      type: ItemType.MATERIAL,
      rarity: Rarity.SR,
      description: '用于SR及以下稀有度卡牌突破的材料。',
      icon: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=breakthrough%20stone%20purple%20rare%20game%20item%20icon&image_size=square',
      maxStack: 999,
      sellable: true,
      sellPrice: 200,
      bindType: BindType.UNBIND,
      usable: false,
    },
    {
      id: 'item_breakthrough_stone_ssr',
      name: '高级突破石',
      type: ItemType.MATERIAL,
      rarity: Rarity.SSR,
      description: '用于SSR及以下稀有度卡牌突破的材料。',
      icon: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=breakthrough%20stone%20golden%20epic%20game%20item%20icon&image_size=square',
      maxStack: 999,
      sellable: true,
      sellPrice: 800,
      bindType: BindType.UNBIND,
      usable: false,
    },
    {
      id: 'item_breakthrough_stone_ur',
      name: '特级突破石',
      type: ItemType.MATERIAL,
      rarity: Rarity.UR,
      description: '用于UR及以下稀有度卡牌突破的材料。',
      icon: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=breakthrough%20stone%20rainbow%20legendary%20game%20item%20icon&image_size=square',
      maxStack: 999,
      sellable: true,
      sellPrice: 3000,
      bindType: BindType.UNBIND,
      usable: false,
    },
    {
      id: 'item_enhance_stone_n',
      name: '初级强化石',
      type: ItemType.MATERIAL,
      rarity: Rarity.N,
      description: '用于装备强化的基础材料。',
      icon: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=enhance%20stone%20gray%20common%20game%20item%20icon&image_size=square',
      maxStack: 999,
      sellable: true,
      sellPrice: 10,
      bindType: BindType.UNBIND,
      usable: false,
    },
    {
      id: 'item_enhance_stone_r',
      name: '中级强化石',
      type: ItemType.MATERIAL,
      rarity: Rarity.R,
      description: '用于装备强化的进阶材料。',
      icon: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=enhance%20stone%20green%20uncommon%20game%20item%20icon&image_size=square',
      maxStack: 999,
      sellable: true,
      sellPrice: 50,
      bindType: BindType.UNBIND,
      usable: false,
    },
    {
      id: 'item_enhance_stone_sr',
      name: '高级强化石',
      type: ItemType.MATERIAL,
      rarity: Rarity.SR,
      description: '用于装备强化的高级材料。',
      icon: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=enhance%20stone%20purple%20rare%20game%20item%20icon&image_size=square',
      maxStack: 999,
      sellable: true,
      sellPrice: 200,
      bindType: BindType.UNBIND,
      usable: false,
    },
    {
      id: 'item_summon_ticket_normal',
      name: '普通召唤券',
      type: ItemType.CONSUMABLE,
      rarity: Rarity.R,
      description: '可进行一次普通召唤。',
      icon: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=summon%20ticket%20blue%20common%20game%20item%20icon&image_size=square',
      maxStack: 999,
      sellable: false,
      sellPrice: 0,
      bindType: BindType.BIND,
      usable: true,
      extraData: { summonType: 'normal' },
    },
    {
      id: 'item_summon_ticket_advanced',
      name: '高级召唤券',
      type: ItemType.CONSUMABLE,
      rarity: Rarity.SR,
      description: '可进行一次高级召唤，获得稀有卡牌的概率更高。',
      icon: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=summon%20ticket%20golden%20rare%20game%20item%20icon&image_size=square',
      maxStack: 999,
      sellable: false,
      sellPrice: 0,
      bindType: BindType.BIND,
      usable: true,
      extraData: { summonType: 'advanced' },
    },
    {
      id: 'item_stamina_potion_small',
      name: '小体力药水',
      type: ItemType.CONSUMABLE,
      rarity: Rarity.N,
      description: '使用后恢复30点体力。',
      icon: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=stamina%20potion%20red%20small%20game%20item%20icon&image_size=square',
      maxStack: 99,
      sellable: true,
      sellPrice: 30,
      bindType: BindType.UNBIND,
      usable: true,
      useEffect: { type: 'gain_currency', value: 30, currencyType: 'stamina' },
    },
    {
      id: 'item_stamina_potion_large',
      name: '大体力药水',
      type: ItemType.CONSUMABLE,
      rarity: Rarity.R,
      description: '使用后恢复100点体力。',
      icon: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=stamina%20potion%20red%20large%20game%20item%20icon&image_size=square',
      maxStack: 99,
      sellable: true,
      sellPrice: 80,
      bindType: BindType.UNBIND,
      usable: true,
      useEffect: { type: 'gain_currency', value: 100, currencyType: 'stamina' },
    },
    {
      id: 'item_fire_crystal',
      name: '火元素结晶',
      type: ItemType.MATERIAL,
      rarity: Rarity.N,
      description: '蕴含火元素力量的结晶，可用于火系卡牌培养。',
      icon: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=fire%20crystal%20red%20element%20game%20item%20icon&image_size=square',
      maxStack: 999,
      sellable: true,
      sellPrice: 15,
      bindType: BindType.UNBIND,
      usable: false,
      extraData: { element: 'fire' },
    },
    {
      id: 'item_water_crystal',
      name: '水元素结晶',
      type: ItemType.MATERIAL,
      rarity: Rarity.N,
      description: '蕴含水元素力量的结晶，可用于水系卡牌培养。',
      icon: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=water%20crystal%20blue%20element%20game%20item%20icon&image_size=square',
      maxStack: 999,
      sellable: true,
      sellPrice: 15,
      bindType: BindType.UNBIND,
      usable: false,
      extraData: { element: 'water' },
    },
    {
      id: 'item_earth_crystal',
      name: '土元素结晶',
      type: ItemType.MATERIAL,
      rarity: Rarity.N,
      description: '蕴含土元素力量的结晶，可用于土系卡牌培养。',
      icon: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=earth%20crystal%20brown%20element%20game%20item%20icon&image_size=square',
      maxStack: 999,
      sellable: true,
      sellPrice: 15,
      bindType: BindType.UNBIND,
      usable: false,
      extraData: { element: 'earth' },
    },
    {
      id: 'item_wind_crystal',
      name: '风元素结晶',
      type: ItemType.MATERIAL,
      rarity: Rarity.N,
      description: '蕴含风元素力量的结晶，可用于风系卡牌培养。',
      icon: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=wind%20crystal%20green%20element%20game%20item%20icon&image_size=square',
      maxStack: 999,
      sellable: true,
      sellPrice: 15,
      bindType: BindType.UNBIND,
      usable: false,
      extraData: { element: 'wind' },
    },
    {
      id: 'item_light_crystal',
      name: '光元素结晶',
      type: ItemType.MATERIAL,
      rarity: Rarity.R,
      description: '蕴含光元素力量的结晶，可用于光系卡牌培养。',
      icon: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=light%20crystal%20yellow%20element%20game%20item%20icon&image_size=square',
      maxStack: 999,
      sellable: true,
      sellPrice: 30,
      bindType: BindType.UNBIND,
      usable: false,
      extraData: { element: 'light' },
    },
    {
      id: 'item_dark_crystal',
      name: '暗元素结晶',
      type: ItemType.MATERIAL,
      rarity: Rarity.R,
      description: '蕴含暗元素力量的结晶，可用于暗系卡牌培养。',
      icon: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=dark%20crystal%20purple%20element%20game%20item%20icon&image_size=square',
      maxStack: 999,
      sellable: true,
      sellPrice: 30,
      bindType: BindType.UNBIND,
      usable: false,
      extraData: { element: 'dark' },
    },
    {
      id: 'item_skill_book_basic',
      name: '初级技能书',
      type: ItemType.MATERIAL,
      rarity: Rarity.R,
      description: '可用于提升普通技能等级。',
      icon: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=skill%20book%20blue%20basic%20game%20item%20icon&image_size=square',
      maxStack: 999,
      sellable: true,
      sellPrice: 100,
      bindType: BindType.UNBIND,
      usable: false,
      extraData: { skillType: 'normal' },
    },
    {
      id: 'item_skill_book_advanced',
      name: '高级技能书',
      type: ItemType.MATERIAL,
      rarity: Rarity.SR,
      description: '可用于提升主动技能等级。',
      icon: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=skill%20book%20purple%20advanced%20game%20item%20icon&image_size=square',
      maxStack: 999,
      sellable: true,
      sellPrice: 300,
      bindType: BindType.UNBIND,
      usable: false,
      extraData: { skillType: 'active' },
    },
    {
      id: 'item_skill_book_ultimate',
      name: '终极技能书',
      type: ItemType.MATERIAL,
      rarity: Rarity.SSR,
      description: '可用于提升终极技能等级。',
      icon: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=skill%20book%20golden%20ultimate%20game%20item%20icon&image_size=square',
      maxStack: 999,
      sellable: true,
      sellPrice: 1000,
      bindType: BindType.UNBIND,
      usable: false,
      extraData: { skillType: 'ultimate' },
    },
  ];
}
